## 1. 基础监听
listeners {
    tcp {
        bind = "0.0.0.0:1883"
    }
}

## 2. HTTP 服务
http_server {
    url = "http://0.0.0.0:8081"
    username = "admin"
    password = "public"
}

## 4. 日志
log {
    level = "info"
}