## 1. 基础监听
listeners {
    tcp {
        bind = "0.0.0.0:1883"
    }
}

## 2. HTTP 服务
http_server {
    url = "http://0.0.0.0:8081"
    username = "admin"
    password = "public"
}

## 3. 规则引擎 (新版标准格式)
## 注意：这里使用 rules (复数)
rules.repub = {
  rules = [
    {
      server = "tcp://localhost:9001"   # 重新发布的 MQTT 服务器地址
      topic = "topic/repub1"                 # 重新发布的主题
      proto_ver = 4                          # MQTT 协议版本
      clientid = "repub_client1"             # 重新发布客户端的客户端 ID
      keepalive = "60s"                      # 重新发布保活时间
      clean_start = true                     # clean_start 标志
      sql = "SELECT * FROM \"#\"" # 规则 SQL
    }
  ]
}

## 4. 日志
log {
    level = "info"
}